circleci:
    # use user and password auth
    type: snowflake
    account: "rc56421.us-east-2"
    user: "{{ env_var('DBT_DATA_MODELING_SNOWFLAKE_USER') }}"
    password: "{{ env_var('DBT_DATA_MODELING_SNOWFLAKE_PASSWORD') }}"
    role: "{{ env_var('DBT_DATA_MODELING_SNOWFLAKE_ROLE') }}"
    database: "{{ env_var('DBT_DATA_MODELING_SNOWFLAKE_DATABASE') }}"
    warehouse: "dbt_wh"
    schema: "raw"
    query_tag: "circleci_dbt"
