version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    steps:
      - checkout
  deploy:
    docker:
      - image: python:3.8

    steps:
      - checkout
- run:
    name: Docker Login
    command: |
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - run:
          name: Setup Snowflake Connection
          command: |
            echo "SNOWSQL_ACCOUNT: $SNOWSQL_ACCOUNT"
            echo "SNOWSQL_USER: $SNOWSQL_USER"
            echo "SNOWSQL_PASSWORD: $SNOWSQL_PASSWORD"

      - run:
          name: Install dbt
          command: |
            pip install dbt
      - run:
          name: Configure dbt Cloud
          command: |
            dbt cloud auth --token 971945e6e76465fbace61e086c53187420a7c473

      - run:
          name: Run dbt
          command: |
            dbt run --select order_summary
      - run:
          name: "Pipeline builded"
          command: echo "Snowflake succeeded!"   


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
